---
- name: Import DB SQL file
  become: yes
  mysql_db:
    name: "{{ item }}"
    state: import
    target: "/vagrant/{{ item }}.sql.gz"
  with_items: "{{ appprovision.databases }}"
  tags: db

- name: Host pre-install tasks
  local_action: "shell {{ item }}"
  with_items: "{{ appprovision.pre_install.host_tasks }}"

- name: Guest install tasks
  shell: "{{ item }}"
  args:
    chdir: "/vagrant"
  environment: "{{ appprovision.install.env_vars | default({}) }}"
  with_items: "{{ appprovision.install.guest_tasks }}"

- name: Make sure app temporary directories are present
  file:
    path: "{{ appprovision.app }}/{{ item }}"
    state: directory
  with_items: "{{ appprovision.temporary_directories }}"

- name: Make sure the ACLs for app directories for webserver user are present
  acl:
    name: "{{ appprovision.app }}/{{ item }}"
    entity: www-data
    etype: user
    permissions: rxw
    state: present
  with_items: "{{ appprovision.temporary_directories }}"

- name: Make sure the ACLs for app directories with default and webserver user are present
  acl:
    name: "{{ appprovision.app }}/{{ item }}"
    entity: www-data
    etype: user
    permissions: rxw
    default: yes
    state: present
  with_items: "{{ appprovision.temporary_directories }}"

- name: Make sure the ACLs for app directories with current user are present
  acl:
    name: "{{ appprovision.app }}/{{ item }}"
    entity: vagrant
    etype: user
    permissions: rxw
    default: yes
    state: present
  with_items: "{{ appprovision.temporary_directories }}"

- name: Copy app files
  shell: "rsync -auAXK --inplace {% for path in appprovision.sync_exclude %}--exclude {{ path }} {% endfor %}/vagrant/ ."
  args:
    chdir: "{{ appprovision.app }}"

- name: Make sure VM symlinks are present
  file:
    src: "/vagrant/{{ item }}"
    path: "{{ appprovision.app }}/{{ item }}"
    state: link
    force: yes
  with_items: "{{ appprovision.symlinks }}"

- name: Make sure App symlinks are present
  file:
    src: "{{ item.source }}"
    path: "{{ appprovision.app }}/{{ item.target }}"
    state: link
    force: yes
  with_items: "{{ appprovision.app_symlinks }}"

- name: Make sure App virtualhosts are present
  become: yes
  file:
    src: "/vagrant/{{ item.path }}/{{ item.name }}.conf"
    path: "/etc/apache2/sites-available/{{ item.name }}.conf"
    state: link
  with_items: "{{ appprovision.virtualhosts }}"
  notify: reload apache

- name: Enable virtualhosts
  become: yes
  command: "a2ensite {{ item.name }}"
  with_items: "{{ appprovision.virtualhosts }}"
  notify: reload apache

- name: Make sure Guest symlinks are present
  become: yes
  file:
    src: "{{ item.src }}"
    path: "{{ item.path }}"
    state: link
  with_items: "{{ appprovision.guest_symlinks | default([]) }}"

- name: Ensure config files are present
  template:
    src: "config.j2"
    dest: "{{ item.dest }}"
  with_items: "{{ appprovision.config | default([]) }}"
  #no_log: True
  tags: config

- name: Host post-install tasks
  local_action: "shell {{ item }}"
  with_items: "{{ appprovision.post_install.host_tasks | default([]) }}"
